spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/tour_planner
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=7f9a8c2d4e6b1a9f3d2e5c8b0a4f7e1d
openrouteservice.apiKey=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjEzZTc1MjcxMTk1ODQ5MjlhNDVmMzU1YTYxY2NmZTQ3IiwiaCI6Im11cm11cjY0In0=
storage.image-dir=./images